export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const CLICKED_PRODUCT = "CLICKED_PRODUCT";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const ADD_RECIPE_NAME = "ADD_RECIPE_NAME";

export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";


export const SAVE_RECIPE_START = "SAVE_RECIPE_START";
export const SAVE_RECIPE_FAIL = "SAVE_RECIPE_FAIL";
export const SAVE_RECIPE_SUCCESS = "SAVE_RECIPE_SUCCESS";

export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPESS_SUCCESS";

export const RECIPE_CLICKED = "RECIPE_CLICKED";


export const CLOSE_SIGN_UP = "CLOSE_SIGN_UP";
export const OPEN_SIGN_UP = "OPEN_SIGN_UP";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL"
export const LOGOUT = "LOGOUT";